name: anne
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_rating_bar: ^4.0.0
  percent_indicator: ^3.0.1
  step_progress_indicator: ^1.0.1
  graphql_flutter: ^5.0.0
  http: ^0.13.0
  http_parser: ^4.0.0
  dio: ^4.0.0
  font_awesome_flutter: ^9.2.0
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.5
  flutter_countdown_timer: ^4.1.0
  carousel_slider: ^4.0.0
  dotted_line: ^3.0.0
  get_it: ^7.1.3
  shimmer: ^2.0.0
  provider: ^5.0.0
  datetime_picker_formfield: ^2.0.0
  infinite_scroll_pagination: ^3.0.1
  modal_bottom_sheet: ^2.0.0
  flutter_screenutil: ^5.0.0
  sms_autofill: ^2.2.0
  transparent_image: ^2.0.0
  extended_masked_text: ^2.1.0
#  cashfree_pg: 2.0.4+24
  dotted_border: ^2.0.0
  geolocator: ^8.0.0
  firebase_messaging: ^11.2.0
  flutter_local_notifications: ^8.2.0
  firebase_analytics: ^8.1.0
  package_info: ^2.0.2
  device_info: ^2.0.0
  flutter_svg: ^0.22.0
  share: ^2.0.4
  firebase_remote_config: ^0.11.0+2
  url_launcher: ^6.0.6
  video_player: ^2.1.6
  chewie: ^1.2.2
  firebase_dynamic_links: ^3.0.2
  pinch_zoom: ^1.0.0
  nertc: ^4.4.7-rc.0
  permission_handler: ^8.3.0
  fluttertoast: ^8.0.8
  file_picker: ^4.2.7
  flutter_launcher_icons: ^0.9.2
  image_picker: ^0.8.4+4
  flutter_html: ^2.1.2
  flutter_native_splash: any
  flutter_braintree: ^2.0.0+10
  flutter_stripe: ^2.0.2
  youtube_player_flutter: ^8.0.0
  flutter_login_facebook: ^1.1.0
  google_sign_in: ^5.2.1
  colorful_safe_area: ^0.3.0
  sign_in_with_apple: ^3.2.0
  collection: ^1.15.0-nullsafety.4
  fijkplayer: ^0.10.1
  extended_image: ^5.1.3
  email_validator: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.jpg"


flutter_native_splash:
  background_image: "assets/images/splashScreen.png"
  fullscreen: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
#    - assets/icon/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
#    - family: Sofia
#      fonts:
#        - asset: assets/fonts/sofia/Sofia Pro Regular Az.otf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
