const EVENT_ONBOARDING = 'Onboarding';
const EVENT_HOME_MAIN_SLIDER = 'HOME_MAIN_SLIDER';
const EVENT_HOME_CATEGORIES = 'HOME_CATEGORIES';
const EVENT_HOME_PROMO_BANNER = 'HOME_PROMO_BANNER';
const EVENT_YOU_MAY_LIKE = 'YOU_MAY_LIKE';
const EVENT_TRENDING = 'TRENDING';

const EVENT_CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
const EVENT_CART_INCREASE_ITEM_COUNT = 'CART_INCREASE_ITEM_COUNT';
const EVENT_CART_DECREASE_ITEM_COUNT = 'CART_DECREASE_ITEM_COUNT';
const EVENT_PAYMENT_SELECTED_TYPE = 'PAYMENT_SELECTED_TYPE';
const EVENT_PAYMENT_TRY_AGAIN = 'PAYMENT_TRY_AGAIN';
const EVENT_ORDER_PLACEMENT_SUCCESS = 'ORDER_PLACEMENT_SUCCESS';
const EVENT_ORDER_PLACEMENT_FAILURE = 'ORDER_PLACEMENT_FAILURE';
const EVENT_ORDER_PLACEMENT_CANCEL = 'ORDER_PLACEMENT_CANCEL';

const EVENT_PRODUCT_DETAILS_ADD_TO_CART = 'PRODUCT_DETAILS_ADD_TO_CART';
const EVENT_PRODUCT_DETAILS_BUY_NOW = 'PRODUCT_DETAILS_BUY_NOW';
const EVENT_PRODUCT_DETAILS_ADD_TO_WISHLIST = 'PRODUCT_DETAILS_ADD_TO_WISHLIST';

const EVENT_SEARCH_SUGGESTIONS_LIST = 'EVENT_SEARCH_SUGGESTIONS_LIST';
const EVENT_SEARCH_SUGGESTION_SELECTED = 'EVENT_SEARCH_SUGGESTION_SELECTED';
const EVENT_SEARCH_TERM_RESULT = 'EVENT_SEARCH_TERM_RESULT';

const EVENT_PRODUCT_LIST_FILTERS = 'EVENT_PRODUCT_LIST_FILTERS';
const EVENT_PRODUCT_LIST_SORTED_BY = 'EVENT_PRODUCT_LIST_SORTED_BY';
const EVENT_PRODUCT_LIST_SELECTED_ITEM = 'EVENT_PRODUCT_LIST_SELECTED_ITEM';
const EVENT_PRODUCT_LIST_SIMILAR_ITEMS = 'EVENT_PRODUCT_LIST_SIMILAR_ITEMS';
const EVENT_PRODUCT_LIST_SELECTED_PAGE = 'EVENT_PRODUCT_LIST_SELECTED_PAGE';

const EVENT_LOGIN_MOBILE_ENTERED = 'LOGIN_MOBILE_ENTERED';
const EVENT_LOGIN_GET_OTP = 'LOGIN_GET_OTP';
const EVENT_LOGIN_OTP_ENTERED = 'LOGIN_OTP_ENTERED';
