 ## Flutter wrapper
 -keep class io.flutter.app.** { *; }
 -keep class io.flutter.plugin.** { *; }
 -keep class io.flutter.util.** { *; }
 -keep class io.flutter.view.** { *; }
 -keep class io.flutter.** { *; }
 -keep class io.flutter.plugins.** { *; }
 -keep class com.shockwave.**
 -keep class com.google.firebase.** { *; }
 -keep class **.zego.**{*;}
 -dontwarn io.flutter.embedding.**
 -keep class com.netease.lava.** {*;}
 -keep class com.netease.yunxin.** {*;}
 -ignorewarnings
